export const SET_EMP_LIST       = 'SET_EMP_LIST' 
export const ADD_EMP            = 'ADD_EMP'
export const UPDATE_EMP         = 'UPDATE_EMP'
export const SET_CUR_PAGE       = 'SET_CUR_PAGE'
export const SET_SELECTED_EMP   = 'SET_SELECTED_EMP'
export const SET_CUR_STEP       = 'SET_CUR_STEP'
export const SET_EMP_DATA       =  'SET_EMP_DATA'
export const REMOVE_EMP         = 'REMOVE_EMP'
